name: integration-tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'release/*'

concurrency:
  group: ci-resource-lock-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-integration-tests:
    name: Run Python integration tests
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run integration tests (headless)
        id: run_integration_tests
        continue-on-error: true
        env:
          PYTHONPATH: ${{ github.workspace }}
          TEST_PATTERN: "IntegrationTests"
        run: |
          FAILED=0
            for file in Run/tests/*${TEST_PATTERN}.py; do
              echo "Running tests in $file"
              if ! python -m pytest -v "$file" --timeout=60; then
                FAILED=1
              fi
            done
              
            if [ $FAILED -ne 0 ]; then
              echo "::warning::Des tests d'intégration ont échoué."
              exit 1
            fi
